### ISSUE TITLE
An external profile from a user I follow already shows the follow button

### ISSUE THREAD

**Issue by aaadonai** [jointwt/goryon#21]
**Describe the bug**
Going to an external user's profile that I follow is showing the follow button

**To Reproduce**
1. Go to the Timeline and find an user you follow that you know is an external user
2. Tap on user avatar to bring the user's profile
3. Look at the Follow button. It shouldn't be there. It should be the Unfollow button instead

**Expected behavior**
I would expect to see the Unfollow user button

**Screenshots**
![image](https://user-images.githubusercontent.com/1087949/93958379-3bebd400-fd0b-11ea-8d93-9576c73dc56b.png)

**Mobile (please complete the following information):**
 Goryon iOS version 1.0.0(17)

**Comment by dooven** [comment]
This should be fixed in https://github.com/jointwt/goryon/pull/59
