### ISSUE TITLE
Default to https scheme

### ISSUE THREAD

**Issue by prologic** [jointwt/goryon#74]

**Comment by dooven** [comment]
Hi James. Where'd you notice where the app is using http as scheme?

**Comment by prologic** [comment]
When registering a new account on a colleague's phone it kept failing until I explicitly put https:// in front of the URL￼

The error message also wasn't very helpful 😁￼

**Comment by prologic** [comment]
@aaadonai What about this one? Can we do something here before we roll a new version?
